(function(d){var k=window.AmazonUIPageJS||window.P,f=k._namespace||k.attributeErrors,a=f?f("DetailPageNostosAssets",""):k;a.guardFatal?a.guardFatal(d)(a,window):a.execute(function(){d(a,window)})})(function(d,k,f){d.when("nostos-device-utils").register("nostos-metrics",function(a){var b=k.ue,g="object"===typeof b&&b.count,e="NostosBadge:"+a.getDeviceType()+":";return{recordClick:function(a){if("object"!==typeof a)throw"Opts is not an object";f!==a.counter&&(a=a.counter)&&g&&b.count(e+a,1)},addCSMTag:function(a){b&&
b.tag&&b.tag(a)}}});"use strict";d.when("ready").register("nostos-device-utils",function(){return{getDeviceType:function(){return"Desktop"}}});d.declare("nostos-buybox-config",{selectors:{buyboxTabSet:"#offerDisplayGroupTabSet",buyboxAccordionRows:"#buyBoxAccordion",nostosBadges:"buyingOptionNostosBadge_feature_div"},tabs:{tab_desktop_buybox_group_1:"#tab_heading_desktop_buybox_group_1",tab_desktop_buybox_group_2:"#tab_heading_desktop_buybox_group_2",tab_mobile_buybox_group_1:"#tab_heading_mobile_buybox_group_1",
tab_mobile_buybox_group_2:"#tab_heading_mobile_buybox_group_2",tab_mobileapp_buybox_group_1:"#tab_heading_mobileapp_buybox_group_1",tab_mobileapp_buybox_group_2:"#tab_heading_mobileapp_buybox_group_2"},accordionRowsToNostos:{newAccordionRow:["NEW_1_nostos_badge","NEW_1_nostos_bolder_badge"],SecondNewAccordionRow:["NEW_2_nostos_badge","NEW_2_nostos_bolder_badge"],pwBuyBoxAccordionRow:["PRIME_WARDROBE_1_nostos_badge"],usedAccordionRow:["USED_1_nostos_badge"],snsAccordionRow:["SNS_1_nostos_badge"],snsAccordionRowMovedUp:["SNS_1_nostos_badge"],
snsAccordionRowMiddle:["SNS_1_nostos_badge"],snsAccordionRowMobileMiddle:["SNS_1_nostos_badge"],snsAccordionRowMobileAppMiddle:["SNS_1_nostos_badge"],dealsAccordionRow:["LIGHTNING_DEAL_1_nostos_badge"],renewedTier1AccordionRow:["RENEWED_TIER_1_1_nostos_badge"],mobile_renewedTier1AccordionRow:["RENEWED_TIER_1_1_nostos_badge"],mobileApp_renewedTier1AccordionRow:["RENEWED_TIER_1_1_nostos_badge"],renewedTier2AccordionRow:["RENEWED_TIER_2_1_nostos_badge"],mobile_renewedTier2AccordionRow:["RENEWED_TIER_2_1_nostos_badge"],
mobileApp_renewedTier2AccordionRow:["RENEWED_TIER_2_1_nostos_badge"],renewedTier3AccordionRow:["RENEWED_TIER_3_1_nostos_badge"],mobile_renewedTier3AccordionRow:["RENEWED_TIER_3_1_nostos_badge"],mobileApp_renewedTier3AccordionRow:["RENEWED_TIER_3_1_nostos_badge"],renewedTier4AccordionRow:["RENEWED_TIER_4_1_nostos_badge"],mobile_renewedTier4AccordionRow:["RENEWED_TIER_4_1_nostos_badge"],mobileApp_renewedTier4AccordionRow:["RENEWED_TIER_4_1_nostos_badge"]},nostosToAccordionRows:{NEW_1_nostos_badge:["newAccordionRow_0",
"newAccordionRow_1","newAccordionRow_2","newAccordionRow_3"],NEW_1_nostos_bolder_badge:["newAccordionRow_0","newAccordionRow_1","newAccordionRow_2","newAccordionRow_3"],NEW_2_nostos_badge:["newAccordionRow_1","newAccordionRow_2","newAccordionRow_3","newAccordionRow_4"],NEW_2_nostos_bolder_badge:["newAccordionRow_1","newAccordionRow_2","newAccordionRow_3","newAccordionRow_4"],PRIME_WARDROBE_1_nostos_badge:["pwBuyBoxAccordionRow"],USED_1_nostos_badge:["usedAccordionRow"],SNS_1_nostos_badge:["snsAccordionRow",
"snsAccordionRowMovedUp","snsAccordionRowMiddle","snsAccordionRowMobileMiddle","snsAccordionRowMobileAppMiddle"],LIGHTNING_DEAL_1_nostos_badge:["dealsAccordionRow"],RENEWED_TIER_1_1_nostos_badge:["renewedTier1AccordionRow","mobile_renewedTier1AccordionRow","mobileApp_renewedTier1AccordionRow"],RENEWED_TIER_2_1_nostos_badge:["renewedTier2AccordionRow","mobile_renewedTier2AccordionRow","mobileApp_renewedTier2AccordionRow"],RENEWED_TIER_3_1_nostos_badge:["renewedTier3AccordionRow","mobile_renewedTier3AccordionRow",
"mobileApp_renewedTier3AccordionRow"],RENEWED_TIER_4_1_nostos_badge:["renewedTier4AccordionRow","mobile_renewedTier4AccordionRow","mobileApp_renewedTier4AccordionRow"]},nostosToSingleOffer:{NEW_1_nostos_badge:["qualifiedBuybox_globalMatchbox_3","qualifiedBuybox_globalMatchbox_2","qualifiedBuybox_globalMatchbox_1","qualifiedBuybox"],NEW_1_nostos_bolder_badge:["qualifiedBuybox_globalMatchbox_3","qualifiedBuybox_globalMatchbox_2","qualifiedBuybox_globalMatchbox_1","qualifiedBuybox"],USED_1_nostos_badge:["used_buybox_desktop",
"used_buybox_mobile","used_buybox_mobileApp"],PICKUP_1_nostos_badge:["pickupOfferDisplay_Desktop","pickupOfferDisplay_Mobile","pickupOfferDisplay_MobileApp"],LIGHTNING_DEAL_1_nostos_badge:["deals_singleOfferDisplay_Desktop","deals_singleOfferDisplay_Mobile","deals_singleOfferDisplay_MobileApp"]}});"use strict";d.when("A","nostos-metrics","nostos-buybox-config","atf").register("nostos-buying-option-controller",function(a,b,g){var e=a.$;b.addCSMTag("buyingOptionNostos");var d,k,m,l,t=function(){d=0<
e(g.selectors.buyboxTabSet).length;k=0<e(g.selectors.buyboxAccordionRows).length;for(var h=document.querySelectorAll("#buyingOptionNostosBadge_feature_div \x3e div, #buyingOptionNostosBolderBadge_feature_div \x3e div, #buyingOptionNostosInlineBadge_feature_div \x3e div"),a=[],c=0;c<h.length;c++)a.push(h[c].id);m=a;if(d)a:{for(var b in g.tabs)if(e(g.tabs[b]).hasClass("a-active")){l=b;break a}l=f}};t();var u=function(h){h=g.nostosToSingleOffer[h];if(h!==f)for(var a=0;a<h.length;a++)if(0<e("#"+h[a]).length){var c=
h[a];if(d){if(document.getElementById(l)!==f&&document.getElementById(l).contains(document.getElementById(c)))return!0}else return!0}return!1},n=function(a){e(a).addClass("aok-hidden")},q=function(a){e(a).removeClass("aok-hidden")},r=function(){for(var a=0;a<m.length;a++){var b=m[a];if(k){a:{var c=g.nostosToAccordionRows[b];if(c!==f)for(var p=0;p<c.length;p++)if(e("#"+c[p]).hasClass("a-accordion-active")){var n=c[p];if(d){if(document.getElementById(l)!==f&&document.getElementById(l).contains(document.getElementById(n))){c=
!0;break a}}else{c=!0;break a}}c=!1}if(c||u(b)){q("#"+m[a]);break}}else if(u(b)){q("#"+m[a]);break}}};r();(function(){a.on("a:tabs:offerDisplayGroup_tabs:select",function(a){n(e("[id$\x3d_nostos_badge], [id$\x3d_nostos_bolder_badge]"));l=a.selectedTab.tabName;r()})})();(function(){a.on("a:accordion:buybox-accordion:select",function(a){n(e("[id$\x3d_nostos_badge], [id$\x3d_nostos_bolder_badge]"));if(a=g.accordionRowsToNostos[a.selectedRow.rowName])for(var b=0;b<a.length;b++)q("#"+a[b])})})();(function(){a.on("a:pageUpdate",
function(){n(e("[id$\x3d_nostos_badge], [id$\x3d_nostos_bolder_badge]"));t();r()})})()})});